### ISSUE TITLE
Considering to Merge?

### ISSUE THREAD

**Issue by chrisspiegl** [kkrishnan90/Node-Media-Server#1]
Hello,

are you considering to bring the API extensions to the main repo for this project?

If not, would it be possible to note in the readme what this fork does differently in a notable way and differentiate it more from the main repo?

Thanks,

Chris

**Comment by hthetiot** [comment]
+1

**Comment by hthetiot** [comment]
See https://github.com/illuspas/Node-Media-Server/pull/361

**Comment by hthetiot** [comment]
It's been merged you can close @chrisspiegl, thank you again.
https://github.com/illuspas/Node-Media-Server/pull/361
